// <auto-generated />
using System;
using App.DataAccessLayer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.DataAccessLayer.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20220713185645_initialV5")]
    partial class initialV5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("App.DataAccessLayer.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientIssuesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientIssuesId");

                    b.ToTable("issues");
                });

            modelBuilder.Entity("App.DataAccessLayer.Models.patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientIssuesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientIssuesId");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("App.DataAccessLayer.Models.PatientIssues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IssuesId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PatientIssues");
                });

            modelBuilder.Entity("App.DataAccessLayer.Models.Issue", b =>
                {
                    b.HasOne("App.DataAccessLayer.Models.PatientIssues", null)
                        .WithMany("Issues")
                        .HasForeignKey("PatientIssuesId");
                });

            modelBuilder.Entity("App.DataAccessLayer.Models.patient", b =>
                {
                    b.HasOne("App.DataAccessLayer.Models.PatientIssues", null)
                        .WithMany("Patients")
                        .HasForeignKey("PatientIssuesId");
                });

            modelBuilder.Entity("App.DataAccessLayer.Models.PatientIssues", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
